INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (1, 'Can add question', 1, 'add_question');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (2, 'Can change question', 1, 'change_question');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (3, 'Can delete question', 1, 'delete_question');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (4, 'Can view question', 1, 'view_question');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (5, 'Can add choice', 2, 'add_choice');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (6, 'Can change choice', 2, 'change_choice');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (7, 'Can delete choice', 2, 'delete_choice');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (8, 'Can view choice', 2, 'view_choice');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (9, 'Can add log entry', 3, 'add_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (10, 'Can change log entry', 3, 'change_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (11, 'Can delete log entry', 3, 'delete_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (12, 'Can view log entry', 3, 'view_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (13, 'Can add permission', 4, 'add_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (14, 'Can change permission', 4, 'change_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (15, 'Can delete permission', 4, 'delete_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (16, 'Can view permission', 4, 'view_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (17, 'Can add group', 5, 'add_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (18, 'Can change group', 5, 'change_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (19, 'Can delete group', 5, 'delete_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (20, 'Can view group', 5, 'view_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (21, 'Can add user', 6, 'add_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (22, 'Can change user', 6, 'change_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (23, 'Can delete user', 6, 'delete_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (24, 'Can view user', 6, 'view_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (25, 'Can add content type', 7, 'add_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (26, 'Can change content type', 7, 'change_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (27, 'Can delete content type', 7, 'delete_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (28, 'Can view content type', 7, 'view_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (29, 'Can add session', 8, 'add_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (30, 'Can change session', 8, 'change_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (31, 'Can delete session', 8, 'delete_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (32, 'Can view session', 8, 'view_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (33, 'Can add world detail', 9, 'add_worlddetail');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (34, 'Can change world detail', 9, 'change_worlddetail');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (35, 'Can delete world detail', 9, 'delete_worlddetail');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (36, 'Can view world detail', 9, 'view_worlddetail');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (37, 'Can add world trait', 10, 'add_worldtrait');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (38, 'Can change world trait', 10, 'change_worldtrait');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (39, 'Can delete world trait', 10, 'delete_worldtrait');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (40, 'Can view world trait', 10, 'view_worldtrait');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (41, 'Can add post', 11, 'add_post');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (42, 'Can change post', 11, 'change_post');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (43, 'Can delete post', 11, 'delete_post');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (44, 'Can view post', 11, 'view_post');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (45, 'Can add campaign', 12, 'add_campaign');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (46, 'Can change campaign', 12, 'change_campaign');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (47, 'Can delete campaign', 12, 'delete_campaign');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (48, 'Can view campaign', 12, 'view_campaign');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (49, 'Can add crewmate', 13, 'add_crewmate');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (50, 'Can change crewmate', 13, 'change_crewmate');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (51, 'Can delete crewmate', 13, 'delete_crewmate');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (52, 'Can view crewmate', 13, 'view_crewmate');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (53, 'Can add crew stash', 14, 'add_crewstash');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (54, 'Can change crew stash', 14, 'change_crewstash');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (55, 'Can delete crew stash', 14, 'delete_crewstash');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (56, 'Can view crew stash', 14, 'view_crewstash');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (57, 'Can add equipment trait', 15, 'add_equipmenttrait');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (58, 'Can change equipment trait', 15, 'change_equipmenttrait');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (59, 'Can delete equipment trait', 15, 'delete_equipmenttrait');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (60, 'Can view equipment trait', 15, 'view_equipmenttrait');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (61, 'Can add gun mod', 16, 'add_gunmod');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (62, 'Can change gun mod', 16, 'change_gunmod');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (63, 'Can delete gun mod', 16, 'delete_gunmod');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (64, 'Can view gun mod', 16, 'view_gunmod');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (65, 'Can add gun sight', 17, 'add_gunsight');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (66, 'Can change gun sight', 17, 'change_gunsight');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (67, 'Can delete gun sight', 17, 'delete_gunsight');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (68, 'Can view gun sight', 17, 'view_gunsight');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (69, 'Can add ship', 18, 'add_ship');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (70, 'Can change ship', 18, 'change_ship');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (71, 'Can delete ship', 18, 'delete_ship');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (72, 'Can view ship', 18, 'view_ship');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (73, 'Can add weapon', 19, 'add_weapon');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (74, 'Can change weapon', 19, 'change_weapon');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (75, 'Can delete weapon', 19, 'delete_weapon');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (76, 'Can view weapon', 19, 'view_weapon');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (77, 'Can add protective device', 20, 'add_protectivedevice');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (78, 'Can change protective device', 20, 'change_protectivedevice');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (79, 'Can delete protective device', 20, 'delete_protectivedevice');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (80, 'Can view protective device', 20, 'view_protectivedevice');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (81, 'Can add item', 21, 'add_item');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (82, 'Can change item', 21, 'change_item');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (83, 'Can delete item', 21, 'delete_item');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (84, 'Can view item', 21, 'view_item');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (85, 'Can add equipment', 22, 'add_equipment');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (86, 'Can change equipment', 22, 'change_equipment');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (87, 'Can delete equipment', 22, 'delete_equipment');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (88, 'Can view equipment', 22, 'view_equipment');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (89, 'Can add crew roster', 23, 'add_crewroster');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (90, 'Can change crew roster', 23, 'change_crewroster');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (91, 'Can delete crew roster', 23, 'delete_crewroster');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (92, 'Can view crew roster', 23, 'view_crewroster');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (93, 'Can add consumable', 24, 'add_consumable');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (94, 'Can change consumable', 24, 'change_consumable');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (95, 'Can delete consumable', 24, 'delete_consumable');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (96, 'Can view consumable', 24, 'view_consumable');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (97, 'Can add species', 25, 'add_species');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (98, 'Can change species', 25, 'change_species');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (99, 'Can delete species', 25, 'delete_species');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (100, 'Can view species', 25, 'view_species');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (101, 'Can add background', 26, 'add_background');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (102, 'Can change background', 26, 'change_background');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (103, 'Can delete background', 26, 'delete_background');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (104, 'Can view background', 26, 'view_background');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (105, 'Can add class', 27, 'add_class');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (106, 'Can change class', 27, 'change_class');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (107, 'Can delete class', 27, 'delete_class');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (108, 'Can view class', 27, 'view_class');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (109, 'Can add motivation', 28, 'add_motivation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (110, 'Can change motivation', 28, 'change_motivation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (111, 'Can delete motivation', 28, 'delete_motivation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (112, 'Can view motivation', 28, 'view_motivation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (113, 'Can add update', 29, 'add_update');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (114, 'Can change update', 29, 'change_update');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (115, 'Can delete update', 29, 'delete_update');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (116, 'Can view update', 29, 'view_update');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (117, 'Can add email address', 30, 'add_emailaddress');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (118, 'Can change email address', 30, 'change_emailaddress');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (119, 'Can delete email address', 30, 'delete_emailaddress');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (120, 'Can view email address', 30, 'view_emailaddress');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (121, 'Can add email confirmation', 31, 'add_emailconfirmation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (122, 'Can change email confirmation', 31, 'change_emailconfirmation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (123, 'Can delete email confirmation', 31, 'delete_emailconfirmation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (124, 'Can view email confirmation', 31, 'view_emailconfirmation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (125, 'Can add social account', 32, 'add_socialaccount');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (126, 'Can change social account', 32, 'change_socialaccount');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (127, 'Can delete social account', 32, 'delete_socialaccount');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (128, 'Can view social account', 32, 'view_socialaccount');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (129, 'Can add social application', 33, 'add_socialapp');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (130, 'Can change social application', 33, 'change_socialapp');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (131, 'Can delete social application', 33, 'delete_socialapp');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (132, 'Can view social application', 33, 'view_socialapp');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (133, 'Can add social application token', 34, 'add_socialtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (134, 'Can change social application token', 34, 'change_socialtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (135, 'Can delete social application token', 34, 'delete_socialtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (136, 'Can view social application token', 34, 'view_socialtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (137, 'Can add profile', 35, 'add_profile');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (138, 'Can change profile', 35, 'change_profile');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (139, 'Can delete profile', 35, 'delete_profile');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (140, 'Can view profile', 35, 'view_profile');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (141, 'is staff', 29, 'is_staff');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (142, 'Can add ship component', 36, 'add_shipcomponent');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (143, 'Can change ship component', 36, 'change_shipcomponent');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (144, 'Can delete ship component', 36, 'delete_shipcomponent');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (145, 'Can view ship component', 36, 'view_shipcomponent');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (146, 'Can add ship hull', 37, 'add_shiphull');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (147, 'Can change ship hull', 37, 'change_shiphull');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (148, 'Can delete ship hull', 37, 'delete_shiphull');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (149, 'Can view ship hull', 37, 'view_shiphull');
