# Generated by Django 3.2.14 on 2022-07-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_app', '0002_auto_20220729_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='species',
            field=models.CharField(choices=[('BH', 'Baseline Human'), ('BT', 'Bot'), ('EN', 'Engineer'), ('KE', "K'Erin"), ('SL', 'Soulless'), ('PC', 'Precursor'), ('FL', 'Feral'), ('SW', 'Swift'), ('DC', 'De-Converted'), ('UA', 'Unity Agent'), ('MP', 'Mysterious Past'), ('HA', 'Hakshan'), ('ST', 'Stalker'), ('HU', 'Hulker'), ('HR', 'Hopeful Rookie'), ('GU', 'Genetic Uplift'), ('MU', 'Mutant'), ('AB', 'Assault Bot'), ('MA', 'Manipulator'), ('PR', 'Primitive'), ('FE', 'Feeler'), ('ES', 'Emo-Suppressed'), ('MI', 'Minor Alien'), ('TR', 'Traveler'), ('EM', 'Empath'), ('BU', 'Bio-upgrade')], default='BH', max_length=200),
        ),
    ]
