# Generated by Django 3.2.14 on 2022-07-30 00:29

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_app', '0004_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', django.contrib.postgres.fields.ranges.IntegerRangeField(default=0)),
                ('name', models.CharField(max_length=300)),
                ('effect', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, size=None)),
                ('resources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, size=None)),
                ('starting_rolls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Motivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', django.contrib.postgres.fields.ranges.IntegerRangeField(default=0)),
                ('name', models.CharField(max_length=300)),
                ('effect', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, size=None)),
                ('resources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, size=None)),
                ('starting_rolls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='background',
            name='description',
        ),
        migrations.AlterField(
            model_name='background',
            name='roll',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(default=0),
        ),
    ]
