# Generated by Django 3.2.14 on 2022-08-03 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crew_app', '0007_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['-created_on'], 'permissions': [('is_staff', 'is staff')]},
        ),
    ]
