# Generated by Django 3.2.14 on 2022-08-03 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crew_app', '0009_auto_20220802_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crewroster',
            old_name='ship_type',
            new_name='ship',
        ),
    ]
