# Generated by Django 3.2.14 on 2022-08-03 21:43

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_app', '0010_rename_ship_type_crewroster_ship'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=600, null=True)),
                ('traits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='ShipHull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WF', 'Worn Freighter'), ('RTT', 'Retired Troop Transport'), ('SAV', 'Strange Alien Vessel'), ('UPS', 'Upgraded Shuttle'), ('RSS', 'Retired Scout Ship'), ('RSV', 'Repurposed Science Vessel'), ('BMV', 'Battered Mining Ship'), ('UMC', 'Unreliable Merchant Cruiser'), ('FDV', 'Former Diplomatic Vessel'), ('ALC', 'Ancient Low-Tech Craft'), ('BSW', 'Built from Salvaged Wrecks'), ('RMS', 'Retired Military Patrol Ship')], max_length=200)),
                ('traits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('hull_points', models.IntegerField()),
                ('debt', models.CharField(max_length=200)),
                ('roll', django.contrib.postgres.fields.ranges.IntegerRangeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ship',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='traits',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='type',
        ),
    ]
