# Generated by Django 3.2.14 on 2022-08-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_app', '0011_auto_20220803_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipcomponent',
            name='description',
            field=models.TextField(),
        ),
    ]
