# Generated by Django 3.2.14 on 2022-08-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_app', '0012_alter_shipcomponent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipcomponent',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
