# Generated by Django 3.2.14 on 2022-08-03 23:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_app', '0014_alter_shipcomponent_traits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipcomponent',
            name='traits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
