# Generated by Django 3.2.14 on 2022-08-04 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew_app', '0015_alter_shipcomponent_traits'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='hull',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crew_app.shiphull'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='hull_points_cur',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='hull_points_max',
            field=models.IntegerField(null=True),
        ),
    ]
