# Generated by Django 3.2.14 on 2022-08-04 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crew_app', '0016_auto_20220803_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiphull',
            old_name='type',
            new_name='hull',
        ),
    ]
