# Generated by Django 3.2.14 on 2022-08-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_app', '0017_rename_type_shiphull_hull'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmate',
            name='image',
            field=models.ImageField(default='default.png', upload_to='crew_pics'),
        ),
    ]
