# Generated by Django 4.0.1 on 2022-07-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_name', models.CharField(max_length=100)),
                ('world_description', models.TextField()),
                ('wild_galaxy', models.BooleanField(default=True)),
                ('auto_roll', models.BooleanField(default=True)),
                ('world_trait_one', models.CharField(max_length=100)),
                ('world_trait_two', models.CharField(max_length=100)),
                ('native_sentient', models.BooleanField(default=True)),
                ('native_sentient_era', models.CharField(choices=[('PH', 'Pre-History'), ('CL', 'Classical'), ('PI', 'Pre-Industrial'), ('IR', 'Industrial Revolution'), ('EC', 'Early Computer Age'), ('CP', 'Computer Age'), ('SF', 'Spacefaring'), ('NL', 'No sentient life')], default='NL', max_length=2)),
                ('colonized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorldTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_die_min', models.CharField(default=0, max_length=4)),
                ('trait_die_max', models.CharField(default=0, max_length=4)),
                ('trait_name', models.CharField(max_length=200)),
                ('trait_description', models.TextField()),
                ('trait_variables', models.CharField(max_length=200, null=True)),
                ('trait_ai_description', models.CharField(max_length=200, null=True)),
                ('traits_conflicting', models.CharField(max_length=200, null=True)),
                ('traits_complementing', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
