UPDATE public.auth_permission SET name = 'Can add question', content_type_id = 1, codename = 'add_question' WHERE id = 1;
UPDATE public.auth_permission SET name = 'Can change question', content_type_id = 1, codename = 'change_question' WHERE id = 2;
UPDATE public.auth_permission SET name = 'Can delete question', content_type_id = 1, codename = 'delete_question' WHERE id = 3;
UPDATE public.auth_permission SET name = 'Can view question', content_type_id = 1, codename = 'view_question' WHERE id = 4;
UPDATE public.auth_permission SET name = 'Can add choice', content_type_id = 2, codename = 'add_choice' WHERE id = 5;
UPDATE public.auth_permission SET name = 'Can change choice', content_type_id = 2, codename = 'change_choice' WHERE id = 6;
UPDATE public.auth_permission SET name = 'Can delete choice', content_type_id = 2, codename = 'delete_choice' WHERE id = 7;
UPDATE public.auth_permission SET name = 'Can view choice', content_type_id = 2, codename = 'view_choice' WHERE id = 8;
UPDATE public.auth_permission SET name = 'Can add log entry', content_type_id = 3, codename = 'add_logentry' WHERE id = 9;
UPDATE public.auth_permission SET name = 'Can change log entry', content_type_id = 3, codename = 'change_logentry' WHERE id = 10;
UPDATE public.auth_permission SET name = 'Can delete log entry', content_type_id = 3, codename = 'delete_logentry' WHERE id = 11;
UPDATE public.auth_permission SET name = 'Can view log entry', content_type_id = 3, codename = 'view_logentry' WHERE id = 12;
UPDATE public.auth_permission SET name = 'Can add permission', content_type_id = 4, codename = 'add_permission' WHERE id = 13;
UPDATE public.auth_permission SET name = 'Can change permission', content_type_id = 4, codename = 'change_permission' WHERE id = 14;
UPDATE public.auth_permission SET name = 'Can delete permission', content_type_id = 4, codename = 'delete_permission' WHERE id = 15;
UPDATE public.auth_permission SET name = 'Can view permission', content_type_id = 4, codename = 'view_permission' WHERE id = 16;
UPDATE public.auth_permission SET name = 'Can add group', content_type_id = 5, codename = 'add_group' WHERE id = 17;
UPDATE public.auth_permission SET name = 'Can change group', content_type_id = 5, codename = 'change_group' WHERE id = 18;
UPDATE public.auth_permission SET name = 'Can delete group', content_type_id = 5, codename = 'delete_group' WHERE id = 19;
UPDATE public.auth_permission SET name = 'Can view group', content_type_id = 5, codename = 'view_group' WHERE id = 20;
UPDATE public.auth_permission SET name = 'Can add user', content_type_id = 6, codename = 'add_user' WHERE id = 21;
UPDATE public.auth_permission SET name = 'Can change user', content_type_id = 6, codename = 'change_user' WHERE id = 22;
UPDATE public.auth_permission SET name = 'Can delete user', content_type_id = 6, codename = 'delete_user' WHERE id = 23;
UPDATE public.auth_permission SET name = 'Can view user', content_type_id = 6, codename = 'view_user' WHERE id = 24;
UPDATE public.auth_permission SET name = 'Can add content type', content_type_id = 7, codename = 'add_contenttype' WHERE id = 25;
UPDATE public.auth_permission SET name = 'Can change content type', content_type_id = 7, codename = 'change_contenttype' WHERE id = 26;
UPDATE public.auth_permission SET name = 'Can delete content type', content_type_id = 7, codename = 'delete_contenttype' WHERE id = 27;
UPDATE public.auth_permission SET name = 'Can view content type', content_type_id = 7, codename = 'view_contenttype' WHERE id = 28;
UPDATE public.auth_permission SET name = 'Can add session', content_type_id = 8, codename = 'add_session' WHERE id = 29;
UPDATE public.auth_permission SET name = 'Can change session', content_type_id = 8, codename = 'change_session' WHERE id = 30;
UPDATE public.auth_permission SET name = 'Can delete session', content_type_id = 8, codename = 'delete_session' WHERE id = 31;
UPDATE public.auth_permission SET name = 'Can view session', content_type_id = 8, codename = 'view_session' WHERE id = 32;
UPDATE public.auth_permission SET name = 'Can add world detail', content_type_id = 9, codename = 'add_worlddetail' WHERE id = 33;
UPDATE public.auth_permission SET name = 'Can change world detail', content_type_id = 9, codename = 'change_worlddetail' WHERE id = 34;
UPDATE public.auth_permission SET name = 'Can delete world detail', content_type_id = 9, codename = 'delete_worlddetail' WHERE id = 35;
UPDATE public.auth_permission SET name = 'Can view world detail', content_type_id = 9, codename = 'view_worlddetail' WHERE id = 36;
UPDATE public.auth_permission SET name = 'Can add world trait', content_type_id = 10, codename = 'add_worldtrait' WHERE id = 37;
UPDATE public.auth_permission SET name = 'Can change world trait', content_type_id = 10, codename = 'change_worldtrait' WHERE id = 38;
UPDATE public.auth_permission SET name = 'Can delete world trait', content_type_id = 10, codename = 'delete_worldtrait' WHERE id = 39;
UPDATE public.auth_permission SET name = 'Can view world trait', content_type_id = 10, codename = 'view_worldtrait' WHERE id = 40;
UPDATE public.auth_permission SET name = 'Can add post', content_type_id = 11, codename = 'add_post' WHERE id = 41;
UPDATE public.auth_permission SET name = 'Can change post', content_type_id = 11, codename = 'change_post' WHERE id = 42;
UPDATE public.auth_permission SET name = 'Can delete post', content_type_id = 11, codename = 'delete_post' WHERE id = 43;
UPDATE public.auth_permission SET name = 'Can view post', content_type_id = 11, codename = 'view_post' WHERE id = 44;
UPDATE public.auth_permission SET name = 'Can add campaign', content_type_id = 12, codename = 'add_campaign' WHERE id = 45;
UPDATE public.auth_permission SET name = 'Can change campaign', content_type_id = 12, codename = 'change_campaign' WHERE id = 46;
UPDATE public.auth_permission SET name = 'Can delete campaign', content_type_id = 12, codename = 'delete_campaign' WHERE id = 47;
UPDATE public.auth_permission SET name = 'Can view campaign', content_type_id = 12, codename = 'view_campaign' WHERE id = 48;
UPDATE public.auth_permission SET name = 'Can add crewmate', content_type_id = 13, codename = 'add_crewmate' WHERE id = 49;
UPDATE public.auth_permission SET name = 'Can change crewmate', content_type_id = 13, codename = 'change_crewmate' WHERE id = 50;
UPDATE public.auth_permission SET name = 'Can delete crewmate', content_type_id = 13, codename = 'delete_crewmate' WHERE id = 51;
UPDATE public.auth_permission SET name = 'Can view crewmate', content_type_id = 13, codename = 'view_crewmate' WHERE id = 52;
UPDATE public.auth_permission SET name = 'Can add crew stash', content_type_id = 14, codename = 'add_crewstash' WHERE id = 53;
UPDATE public.auth_permission SET name = 'Can change crew stash', content_type_id = 14, codename = 'change_crewstash' WHERE id = 54;
UPDATE public.auth_permission SET name = 'Can delete crew stash', content_type_id = 14, codename = 'delete_crewstash' WHERE id = 55;
UPDATE public.auth_permission SET name = 'Can view crew stash', content_type_id = 14, codename = 'view_crewstash' WHERE id = 56;
UPDATE public.auth_permission SET name = 'Can add equipment trait', content_type_id = 15, codename = 'add_equipmenttrait' WHERE id = 57;
UPDATE public.auth_permission SET name = 'Can change equipment trait', content_type_id = 15, codename = 'change_equipmenttrait' WHERE id = 58;
UPDATE public.auth_permission SET name = 'Can delete equipment trait', content_type_id = 15, codename = 'delete_equipmenttrait' WHERE id = 59;
UPDATE public.auth_permission SET name = 'Can view equipment trait', content_type_id = 15, codename = 'view_equipmenttrait' WHERE id = 60;
UPDATE public.auth_permission SET name = 'Can add gun mod', content_type_id = 16, codename = 'add_gunmod' WHERE id = 61;
UPDATE public.auth_permission SET name = 'Can change gun mod', content_type_id = 16, codename = 'change_gunmod' WHERE id = 62;
UPDATE public.auth_permission SET name = 'Can delete gun mod', content_type_id = 16, codename = 'delete_gunmod' WHERE id = 63;
UPDATE public.auth_permission SET name = 'Can view gun mod', content_type_id = 16, codename = 'view_gunmod' WHERE id = 64;
UPDATE public.auth_permission SET name = 'Can add gun sight', content_type_id = 17, codename = 'add_gunsight' WHERE id = 65;
UPDATE public.auth_permission SET name = 'Can change gun sight', content_type_id = 17, codename = 'change_gunsight' WHERE id = 66;
UPDATE public.auth_permission SET name = 'Can delete gun sight', content_type_id = 17, codename = 'delete_gunsight' WHERE id = 67;
UPDATE public.auth_permission SET name = 'Can view gun sight', content_type_id = 17, codename = 'view_gunsight' WHERE id = 68;
UPDATE public.auth_permission SET name = 'Can add ship', content_type_id = 18, codename = 'add_ship' WHERE id = 69;
UPDATE public.auth_permission SET name = 'Can change ship', content_type_id = 18, codename = 'change_ship' WHERE id = 70;
UPDATE public.auth_permission SET name = 'Can delete ship', content_type_id = 18, codename = 'delete_ship' WHERE id = 71;
UPDATE public.auth_permission SET name = 'Can view ship', content_type_id = 18, codename = 'view_ship' WHERE id = 72;
UPDATE public.auth_permission SET name = 'Can add weapon', content_type_id = 19, codename = 'add_weapon' WHERE id = 73;
UPDATE public.auth_permission SET name = 'Can change weapon', content_type_id = 19, codename = 'change_weapon' WHERE id = 74;
UPDATE public.auth_permission SET name = 'Can delete weapon', content_type_id = 19, codename = 'delete_weapon' WHERE id = 75;
UPDATE public.auth_permission SET name = 'Can view weapon', content_type_id = 19, codename = 'view_weapon' WHERE id = 76;
UPDATE public.auth_permission SET name = 'Can add protective device', content_type_id = 20, codename = 'add_protectivedevice' WHERE id = 77;
UPDATE public.auth_permission SET name = 'Can change protective device', content_type_id = 20, codename = 'change_protectivedevice' WHERE id = 78;
UPDATE public.auth_permission SET name = 'Can delete protective device', content_type_id = 20, codename = 'delete_protectivedevice' WHERE id = 79;
UPDATE public.auth_permission SET name = 'Can view protective device', content_type_id = 20, codename = 'view_protectivedevice' WHERE id = 80;
UPDATE public.auth_permission SET name = 'Can add item', content_type_id = 21, codename = 'add_item' WHERE id = 81;
UPDATE public.auth_permission SET name = 'Can change item', content_type_id = 21, codename = 'change_item' WHERE id = 82;
UPDATE public.auth_permission SET name = 'Can delete item', content_type_id = 21, codename = 'delete_item' WHERE id = 83;
UPDATE public.auth_permission SET name = 'Can view item', content_type_id = 21, codename = 'view_item' WHERE id = 84;
UPDATE public.auth_permission SET name = 'Can add equipment', content_type_id = 22, codename = 'add_equipment' WHERE id = 85;
UPDATE public.auth_permission SET name = 'Can change equipment', content_type_id = 22, codename = 'change_equipment' WHERE id = 86;
UPDATE public.auth_permission SET name = 'Can delete equipment', content_type_id = 22, codename = 'delete_equipment' WHERE id = 87;
UPDATE public.auth_permission SET name = 'Can view equipment', content_type_id = 22, codename = 'view_equipment' WHERE id = 88;
UPDATE public.auth_permission SET name = 'Can add crew roster', content_type_id = 23, codename = 'add_crewroster' WHERE id = 89;
UPDATE public.auth_permission SET name = 'Can change crew roster', content_type_id = 23, codename = 'change_crewroster' WHERE id = 90;
UPDATE public.auth_permission SET name = 'Can delete crew roster', content_type_id = 23, codename = 'delete_crewroster' WHERE id = 91;
UPDATE public.auth_permission SET name = 'Can view crew roster', content_type_id = 23, codename = 'view_crewroster' WHERE id = 92;
UPDATE public.auth_permission SET name = 'Can add consumable', content_type_id = 24, codename = 'add_consumable' WHERE id = 93;
UPDATE public.auth_permission SET name = 'Can change consumable', content_type_id = 24, codename = 'change_consumable' WHERE id = 94;
UPDATE public.auth_permission SET name = 'Can delete consumable', content_type_id = 24, codename = 'delete_consumable' WHERE id = 95;
UPDATE public.auth_permission SET name = 'Can view consumable', content_type_id = 24, codename = 'view_consumable' WHERE id = 96;
UPDATE public.auth_permission SET name = 'Can add species', content_type_id = 25, codename = 'add_species' WHERE id = 97;
UPDATE public.auth_permission SET name = 'Can change species', content_type_id = 25, codename = 'change_species' WHERE id = 98;
UPDATE public.auth_permission SET name = 'Can delete species', content_type_id = 25, codename = 'delete_species' WHERE id = 99;
UPDATE public.auth_permission SET name = 'Can view species', content_type_id = 25, codename = 'view_species' WHERE id = 100;
UPDATE public.auth_permission SET name = 'Can add background', content_type_id = 26, codename = 'add_background' WHERE id = 101;
UPDATE public.auth_permission SET name = 'Can change background', content_type_id = 26, codename = 'change_background' WHERE id = 102;
UPDATE public.auth_permission SET name = 'Can delete background', content_type_id = 26, codename = 'delete_background' WHERE id = 103;
UPDATE public.auth_permission SET name = 'Can view background', content_type_id = 26, codename = 'view_background' WHERE id = 104;
UPDATE public.auth_permission SET name = 'Can add class', content_type_id = 27, codename = 'add_class' WHERE id = 105;
UPDATE public.auth_permission SET name = 'Can change class', content_type_id = 27, codename = 'change_class' WHERE id = 106;
UPDATE public.auth_permission SET name = 'Can delete class', content_type_id = 27, codename = 'delete_class' WHERE id = 107;
UPDATE public.auth_permission SET name = 'Can view class', content_type_id = 27, codename = 'view_class' WHERE id = 108;
UPDATE public.auth_permission SET name = 'Can add motivation', content_type_id = 28, codename = 'add_motivation' WHERE id = 109;
UPDATE public.auth_permission SET name = 'Can change motivation', content_type_id = 28, codename = 'change_motivation' WHERE id = 110;
UPDATE public.auth_permission SET name = 'Can delete motivation', content_type_id = 28, codename = 'delete_motivation' WHERE id = 111;
UPDATE public.auth_permission SET name = 'Can view motivation', content_type_id = 28, codename = 'view_motivation' WHERE id = 112;
UPDATE public.auth_permission SET name = 'Can add update', content_type_id = 29, codename = 'add_update' WHERE id = 113;
UPDATE public.auth_permission SET name = 'Can change update', content_type_id = 29, codename = 'change_update' WHERE id = 114;
UPDATE public.auth_permission SET name = 'Can delete update', content_type_id = 29, codename = 'delete_update' WHERE id = 115;
UPDATE public.auth_permission SET name = 'Can view update', content_type_id = 29, codename = 'view_update' WHERE id = 116;
UPDATE public.auth_permission SET name = 'Can add email address', content_type_id = 30, codename = 'add_emailaddress' WHERE id = 117;
UPDATE public.auth_permission SET name = 'Can change email address', content_type_id = 30, codename = 'change_emailaddress' WHERE id = 118;
UPDATE public.auth_permission SET name = 'Can delete email address', content_type_id = 30, codename = 'delete_emailaddress' WHERE id = 119;
UPDATE public.auth_permission SET name = 'Can view email address', content_type_id = 30, codename = 'view_emailaddress' WHERE id = 120;
UPDATE public.auth_permission SET name = 'Can add email confirmation', content_type_id = 31, codename = 'add_emailconfirmation' WHERE id = 121;
UPDATE public.auth_permission SET name = 'Can change email confirmation', content_type_id = 31, codename = 'change_emailconfirmation' WHERE id = 122;
UPDATE public.auth_permission SET name = 'Can delete email confirmation', content_type_id = 31, codename = 'delete_emailconfirmation' WHERE id = 123;
UPDATE public.auth_permission SET name = 'Can view email confirmation', content_type_id = 31, codename = 'view_emailconfirmation' WHERE id = 124;
UPDATE public.auth_permission SET name = 'Can add social account', content_type_id = 32, codename = 'add_socialaccount' WHERE id = 125;
UPDATE public.auth_permission SET name = 'Can change social account', content_type_id = 32, codename = 'change_socialaccount' WHERE id = 126;
UPDATE public.auth_permission SET name = 'Can delete social account', content_type_id = 32, codename = 'delete_socialaccount' WHERE id = 127;
UPDATE public.auth_permission SET name = 'Can view social account', content_type_id = 32, codename = 'view_socialaccount' WHERE id = 128;
UPDATE public.auth_permission SET name = 'Can add social application', content_type_id = 33, codename = 'add_socialapp' WHERE id = 129;
UPDATE public.auth_permission SET name = 'Can change social application', content_type_id = 33, codename = 'change_socialapp' WHERE id = 130;
UPDATE public.auth_permission SET name = 'Can delete social application', content_type_id = 33, codename = 'delete_socialapp' WHERE id = 131;
UPDATE public.auth_permission SET name = 'Can view social application', content_type_id = 33, codename = 'view_socialapp' WHERE id = 132;
UPDATE public.auth_permission SET name = 'Can add social application token', content_type_id = 34, codename = 'add_socialtoken' WHERE id = 133;
UPDATE public.auth_permission SET name = 'Can change social application token', content_type_id = 34, codename = 'change_socialtoken' WHERE id = 134;
UPDATE public.auth_permission SET name = 'Can delete social application token', content_type_id = 34, codename = 'delete_socialtoken' WHERE id = 135;
UPDATE public.auth_permission SET name = 'Can view social application token', content_type_id = 34, codename = 'view_socialtoken' WHERE id = 136;
UPDATE public.auth_permission SET name = 'Can add profile', content_type_id = 35, codename = 'add_profile' WHERE id = 137;
UPDATE public.auth_permission SET name = 'Can change profile', content_type_id = 35, codename = 'change_profile' WHERE id = 138;
UPDATE public.auth_permission SET name = 'Can delete profile', content_type_id = 35, codename = 'delete_profile' WHERE id = 139;
UPDATE public.auth_permission SET name = 'Can view profile', content_type_id = 35, codename = 'view_profile' WHERE id = 140;
UPDATE public.auth_permission SET name = 'is staff', content_type_id = 29, codename = 'is_staff' WHERE id = 141;
UPDATE public.auth_permission SET name = 'Can add ship component', content_type_id = 36, codename = 'add_shipcomponent' WHERE id = 142;
UPDATE public.auth_permission SET name = 'Can change ship component', content_type_id = 36, codename = 'change_shipcomponent' WHERE id = 143;
UPDATE public.auth_permission SET name = 'Can delete ship component', content_type_id = 36, codename = 'delete_shipcomponent' WHERE id = 144;
UPDATE public.auth_permission SET name = 'Can view ship component', content_type_id = 36, codename = 'view_shipcomponent' WHERE id = 145;
UPDATE public.auth_permission SET name = 'Can add ship hull', content_type_id = 37, codename = 'add_shiphull' WHERE id = 146;
UPDATE public.auth_permission SET name = 'Can change ship hull', content_type_id = 37, codename = 'change_shiphull' WHERE id = 147;
UPDATE public.auth_permission SET name = 'Can delete ship hull', content_type_id = 37, codename = 'delete_shiphull' WHERE id = 148;
UPDATE public.auth_permission SET name = 'Can view ship hull', content_type_id = 37, codename = 'view_shiphull' WHERE id = 149;
